/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const CalorieEntry = IDL.Record({
  'date' : IDL.Text,
  'calories' : IDL.Nat,
});
export const WeightEntry = IDL.Record({
  'weight' : IDL.Float64,
  'date' : IDL.Text,
});
export const WorkoutEntry = IDL.Record({
  'date' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'exercise' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCalorieEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addWeightEntry' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'addWorkoutEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCalorieEntries' : IDL.Func([], [IDL.Vec(CalorieEntry)], ['query']),
  'getTargetWeight' : IDL.Func([], [IDL.Float64], ['query']),
  'getWeightEntries' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
  'getWorkoutEntries' : IDL.Func([], [IDL.Vec(WorkoutEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setTargetWeight' : IDL.Func([IDL.Float64], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const CalorieEntry = IDL.Record({ 'date' : IDL.Text, 'calories' : IDL.Nat });
  const WeightEntry = IDL.Record({ 'weight' : IDL.Float64, 'date' : IDL.Text });
  const WorkoutEntry = IDL.Record({
    'date' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'exercise' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCalorieEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addWeightEntry' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'addWorkoutEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCalorieEntries' : IDL.Func([], [IDL.Vec(CalorieEntry)], ['query']),
    'getTargetWeight' : IDL.Func([], [IDL.Float64], ['query']),
    'getWeightEntries' : IDL.Func([], [IDL.Vec(WeightEntry)], ['query']),
    'getWorkoutEntries' : IDL.Func([], [IDL.Vec(WorkoutEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setTargetWeight' : IDL.Func([IDL.Float64], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };