/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalorieEntry { 'date' : string, 'calories' : bigint }
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightEntry { 'weight' : number, 'date' : string }
export interface WorkoutEntry {
  'date' : string,
  'reps' : bigint,
  'sets' : bigint,
  'exercise' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCalorieEntry' : ActorMethod<[string, bigint], undefined>,
  'addWeightEntry' : ActorMethod<[string, number], undefined>,
  'addWorkoutEntry' : ActorMethod<[string, string, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCalorieEntries' : ActorMethod<[], Array<CalorieEntry>>,
  'getTargetWeight' : ActorMethod<[], number>,
  'getWeightEntries' : ActorMethod<[], Array<WeightEntry>>,
  'getWorkoutEntries' : ActorMethod<[], Array<WorkoutEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setTargetWeight' : ActorMethod<[number], undefined>,
  'submitContact' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];